### ISSUE TITLE
Can we mock a non-public method?

### ISSUE THREAD

**Issue by jeetendrajaiswal** [vanderkleij/Smocks#13]
How can we mock below methods?
```C#
protected internal bool test()
{
   return false;
}
     
static protected internal bool test(string a)
{
	return true;    
}
```

Kindly provide a solution for the above query....

**Comment by vanderkleij** [comment]
This is currently not supported, and will most likely not be supported in the near future. Smock's primary goal is not to be a full-featured mocking framework, but rather to help mocking (public static) code that is out of your control and cannot be mocked using conventional mocking frameworks. Good  examples are `DateTime.Now`, `Dns.GetHostName`, `Console.WriteLine`, etc.

For now, consider mocking the public method(s) invoking the private methods, refactoring the code to allow for mocking, or using [moq](https://github.com/Moq/moq4) (which can mock protected methods) for these cases.

**Comment by jeetendrajaiswal** [comment]
Thanks :)
