### ISSUE TITLE
Progress on event support

### ISSUE THREAD

**Issue by Sephizor** [vanderkleij/Smocks#15]
Hello! Would you be able to provide any update on support for raising mock events? It's the only thing preventing me from being able to use this otherwise brilliant library at the moment.

**Comment by vanderkleij** [comment]
I am yet to start on this feature. One of the reasons why it's taking a while, is that I'm not 100% sure on how this should work. Could you describe your use case, so that we can get a basic idea of what functionality is required?

**Comment by Sephizor** [comment]
I'm trying to mock out a class which emits some events which I subscribe to from my code under test. These event handlers in turn call some callback functions which I want to assert have been called.

As it stands, most of the class I'm trying to mock, including the events, is not marked as virtual so I cannot raise them using Moq or other similar frameworks.

Where normally if it was marked as virtual in Moq I could do:

`new Mock<SomeClass>().Raise(x => x.EventName += null)`

I was hoping to use Smocks to get around the restriction. Sort of like:

```
Smock.Run(c =>
{
  c.Raise(() => new Mock<SomeClass>().Object.EventName += null);
});
```

**Comment by vanderkleij** [comment]
Thanks, that's very helpful @Sephizor. I'll move event support to the top of the roadmap. I cannot really provide an estimation of when it will be done however, as I'm rather busy and don't have a lot of spare time to work on this.

**Comment by Sephizor** [comment]
Thanks for that. In the meantime, I'll have a look at Fakes in the VS Enterprise trial with the goal of moving to Smocks when event support makes it in. Just trying to come up with a solution for mocking some very spaghetti code.

**Comment by vanderkleij** [comment]
For anyone interested: preliminary support for event will be added somewhere within the next 3 weeks.

**Comment by vanderkleij** [comment]
Event support is done and [available on nuget](https://www.nuget.org/packages/Smocks/). The syntax is quick similar to Moq's, albeit slightly different:

```C#
Smock.Run(context =>
{
    context.Raise(() => Console.CancelKeyPress += null, () => Console.CancelKeyPress -= null, default(EventArgs));
});
```

Please check out [the unit tests](https://github.com/vanderkleij/Smocks/blob/master/Source/Smocks.Tests/EventsTests.cs) for more examples on how to use it.

**Comment by Sephizor** [comment]
Awesome stuff! Thank you very much for adding this!
