### ISSUE TITLE
Shims do not affect events

### ISSUE THREAD

**Issue by Stoom** [vanderkleij/Smocks#3]
While shimming DateTime.UtcNow I notice if it is used when an event is fired then the shim is not applied.

**Comment by vanderkleij** [comment]
Thanks for reporting this, @Stoom. Do you have a minimal code example that illustrates the problem?

**Comment by Stoom** [comment]
Yes, let me spin something up later today on the project I was working on and I will post back.

**Comment by Stoom** [comment]
I dug deeper into this and found out it is not a bug, sorry for the false positive.
