### ISSUE TITLE
Does smocks support concurrency?

### ISSUE THREAD

**Issue by ericbrumfield** [vanderkleij/Smocks#4]
This is my first issue I've created and am new to github, so my apologies if this isn't the correct way to ask a question about smocks.  Our test runners we use currently are running in parallel and I'm investigating Smocks as a Microsoft Fakes replacement, which MS Fakes doesn't support concurrency.

Does Smocks support concurrency?  The behavior I'm seeing in a quick prototype/test run make me believe that it does as some tests that previously would intermittently fail with MS Fakes no longer do after switching them to use Smocks.

Appreciate the help!

**Comment by vanderkleij** [comment]
I haven't tested this, but concurrency should not be an issue indeed. Every `Smock.Run` call runs in a separate AppDomain and therefore should not interfere any other concurrent invocations.

**Comment by ericbrumfield** [comment]
I assumed it was loading into individual AppDomains on each Smock.Run.. That's awesome, thanks!
