### ISSUE TITLE
Method under the test throws "InvalidProgramException - Common Language Runtime detects invaild program" exception.

### ISSUE THREAD

**Issue by jeetendrajaiswal** [vanderkleij/Smocks#8]
I have one issue. 
Method under the test throws "InvalidProgramException - Common Language Runtime detects invaild program" exception.

Calling the same method outside the smock context, works fine.
From my search, I found that this exception occurs when there is mismatch in generated IL.

Just to know, is this problem relates to Smock?

**Comment by vanderkleij** [comment]
Yes, it most likely is. Smocks generates IL, and given its experimental nature might accidentally generate invalid IL under certain circumstances. In order to fix it, I'll need some (minimal) sample code that triggers the issue. Can you provide some sample code?

**Comment by jeetendrajaiswal** [comment]
Thanks for the reply....
I have created a sample application to replicate the above issue.
Kindly let me know how can i provide you that sample application as i m not able to upload the application in this conversation.

**Comment by vanderkleij** [comment]
Ideally, the sample should be compact enough to just copy/paste the relevant parts in a comment here. If the sample cannot be reduced any further, how about dumping the sample in a github repository and linking it here?

**Comment by jeetendrajaiswal** [comment]
Thanks for the reply....
Below  is the sample code to replicate the issue...
Also, attached is screenshot of the error....
Please provide a solution to this issue...
![error](https://cloud.githubusercontent.com/assets/13312649/10214595/5bb077be-6837-11e5-8e1a-e134bba98632.png)

Create a solution named "TestSolution"
It will consist of 3 projects - 2 class library and 1 unit test

Project1: Connection (Class Library)
Class Name: ClassConnection
namespace Entities
{  
    public class ClassConnection
    {
       public static Processes.ClassDatabase db; 
    }
}

Class Name: ClassDatabase
namespace Processes
{
	public abstract class ClassDatabase
	{
		public DataSet Fetch(IDbCommand val1, bool val2)
		{           
                DataSet dataset = new DataSet();
                //Write some code
                return dataset;	
		}
	}


	


Project2: Entities (Class Library)
Interface Name: EntityInterface
	
namespace Entities
{
public interface EntityInterface
{
      int ID 
      {
         get;
         set;
      }

      string Description 
      {
         get;
      }
   }
}
	


Project3: TestUsingSmock (Unit Test Project)
1)	Create a new Folder “A”
Under folder “A”, create a new class with name “EmployeeEntity”

namespace Entities
{
    internal class EmployeeEntity : EntityInterface
    {
        public EmployeeEntity()
        {
        }

        public EmployeeEntity(int ID)
        {
            this.id = ID;
        }

        private readonly int id;

        public int Id
        {
            get { return this.id; }
        }

        int EntityInterface.ID
        {
            get { return this.Id; }
            set { ; }
        }

        string EntityInterface.Description
        {
            get { return null; }
        }
    }
}


	
2)	Create a new Folder “B”
Under folder “B”, create a new class with name “EmployeeProcess”

namespace Processes
{
    internal sealed class EmployeeProcess
    {
        public Result Load(EntityInterface ei, DateTime date)
        {
            Result res = Result.Failure;
            DataSet Data = null;
            if ((ei != null) && (ei.ID != 0))
            {
                IDbCommand command = null;

                Data = ClassConnection.db.Fetch(command, false);

                res = Result.Success;
            }
            return res;
        }
    }

    public enum Result
    {
        Failure,
        Success
    };
}

3)	Create a unit test file “UnitTest1.cs”
namespace TestUsingSmock
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Smock.Run(context =>
            {
                EmployeeProcess es = new EmployeeProcess();
                
                Result loaded;
                
                context.Setup(() => Entities.ClassConnection.db.Fetch(Smocks.Matching.It.IsAny<IDbCommand>(), Smocks.Matching.It.IsAny<Boolean>())).Returns((DataSet)null); 

//load dataset with some value if needed

                loaded = es.Load(new EmployeeEntity(1), DateTime.Today);
                
                Assert.AreEqual(Result.Success, loaded);
            });
        }
    }
}

**Comment by vanderkleij** [comment]
Thanks for reporting this issue, I was able to reproduce it using the sample code. I will look into this in more details and provide a fix.

**Comment by jeetendrajaiswal** [comment]
Thanks....
Request u to pls provide a solution asap as we r blocked in using this tool bcoz of this issue..

**Comment by vanderkleij** [comment]
This issue turned out to be [a problem with Mono Cecil](https://groups.google.com/forum/#!topic/mono-cecil/v6LfFLj9eAE). There's a workaround that I applied to fix this issue. I will release a new Smocks nuget package, containing the fix, in the next few days.

**Comment by vanderkleij** [comment]
The [Smocks nuget package 0.4.15](https://www.nuget.org/packages/Smocks/) contains the fix for this issue and is available now.

**Comment by jeetendrajaiswal** [comment]
Thanks.. :)

**Comment by jeetendrajaiswal** [comment]
I downloaded the latest Smocks nuget package 0.4.15 and tried to run the tests.
However, even the existing tests (which were working properly with previous version of smocks) also stopped working and the below error message is displayed.

"An exception of type 'System.NotSupportedException' occurred in Smocks.dll but was not handled in user code

Additional information: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information."

Kindly check and resolve it asap.

Thanks
